<?php namespace BytePerfect\WordPress\Theme\Tehnokrat\Components\Pages;

use BytePerfect\WordPress\Theme\Tehnokrat\Tehnokrat;

defined( 'ABSPATH' ) || exit;

class Archive_Page extends Abstract_Page {
	protected function setup_actions() {
		parent::setup_actions(); // TODO: Change the autogenerated stub

		add_action( 'pre_get_posts', [ $this, 'set_posts_per_page' ] );
	}

	protected function enqueue_styles() {
		wp_enqueue_style( "{$this->identifier}-home" );
	}

	protected function enqueue_scripts() {
		/* @global Tehnokrat $tehnokrat */
		global $tehnokrat;

		wp_enqueue_script( "{$this->identifier}-readmore" );
		wp_enqueue_script( "{$this->identifier}-match-height" );
		wp_enqueue_script( "{$this->identifier}-slick" );
		wp_enqueue_script( "{$this->identifier}-main" );

		wp_localize_script( "{$this->identifier}-main", "{$this->identifier}_script", [
			'slickPrevArrow' => '<button type="button" class="slick-prev pull-left"><img src="' . get_template_directory_uri() . '/img/Arrow.png' . '" alt="" /></button>',
			'slickNextArrow' => '<button type="button" class="slick-next pull-right"><img src="' . get_template_directory_uri() . '/img/Arrow.png' . '" alt="" /></button>',
			'mapIcon'        => get_template_directory_uri() . '/img/map-icon.png',
		] );

		wp_localize_script(
			"{$this->identifier}-script",
			"{$this->identifier}",
			array(
				'ajax_url'                  => admin_url( 'admin-ajax.php' ),
				'nonce'                     => wp_create_nonce( $this->identifier ),
				'exchange_rate'             => $tehnokrat->get_setting( 'main', 'usd_to_uah' ),
				'bank_transfer_fee'         => 1 + $tehnokrat->get_setting( 'main',
						'bank_transfer_fee' ) / 100,
				'products_timestamp_before' => microtime(),
				'products'                  => wp_json_encode( $tehnokrat->get_category_products() ),
				'product_attributes'        => (array) $tehnokrat->get_setting( 'product_attributes', 'attributes' ),
				'products_timestamp_after'  => microtime(),
				'cities'                    => $this->get_cities(),
				'strings'                   => $tehnokrat->get_translation_strings(),
				'label_colors'              => $tehnokrat->get_label_colors(),
			)
		);
	}

	/**
	 * @param \WP_Query $wp_query
	 */
	public function set_posts_per_page( $wp_query ) {
		if ( $wp_query->is_main_query() && $wp_query->is_tax( 'product_cat' ) ) {
			$wp_query->query_vars['posts_per_page'] = - 1;
		}
	}

	protected function get_cities() {
		/**
		 * @global Tehnokrat $tehnokrat
		 */
		global $tehnokrat;

		$cities = $tehnokrat->get_setting( 'installment_payments', 'installment_payments_cities' );
		if ( empty( $cities ) ) {
			$cities = array();
		} else {
			$cities = preg_split( '/\r\n|\r|\n/', $cities );
			$cities = array_map( 'trim', $cities );
		}

		return $cities;
	}
}
